[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "exqudens-serial"
version = "1.0.0"
description = "Exqudens Python Serial"
requires-python = ">=3"

[tool.pdm.build]
includes = ["src"]
package-dir = "src"
